### ISSUE TITLE
"This is not a valid plugin" with Omeka 2.2.2

### ISSUE THREAD

**Issue by bkalish** [waynegraham/omeka-google-analytics#5]
We are trying to install this plugin but we keep getting the message "This is not a valid plugin" on the plugin page in the dashboard. We have tried both installing from the the zip file and cloning with git.

The files seem to have identical permissions to those in other installed plugins which are running fine, so I don't think it is a permission issue.

**Comment by bkalish** [comment]
This problem was fixed by renaming the plugin directory to "GoogleAnalytics". It would be very helpful to include this information in the readme!

**Comment by waynegraham** [comment]
Thanks @bkalish. Documentation was one of the reasons I never put this on the Omeka plugin directory. More than happy to integrate any updates you might have if you have some time to dedicate to this.

**Comment by bkalish** [comment]
Thanks. I've updated the README in a forked repository and created a pull request.

**Comment by waynegraham** [comment]
Thanks for doing this! Might go ahead and post this to the addon directory for Omeka
