### ISSUE TITLE
The script tag is output twice, resulting in invalid javascript

### ISSUE THREAD

**Issue by bkalish** [waynegraham/omeka-google-analytics#7]
There is any easy fix. I will have the pull request momentarily.

**Comment by bkalish** [comment]
Interestingly this was already fixed in 32b6755b521d23ffa74c64db84ca711dbce5b4a7 and then overwritten later. (I think in 32b6755b521d23ffa74c64db84ca711dbce5b4a7)

**Comment by waynegraham** [comment]
Thanks @bkalish. IIRC there was a change with the `queue_js_string` at some point and I put it back, but that seems to no longer be the case.
